/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Canvas, useFrame } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Model.glb')
  useFrame((state, delta) => (group.current.rotation.z += 0.00))

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['Object1-Mesh'].geometry} material={materials.ligrey} />
      <mesh geometry={nodes['Object1-Mesh_1'].geometry} material={materials.Gray} />
      /* monitor screen mesh */
      <mesh geometry={nodes['Object1-Mesh_2'].geometry} material={materials.Black} />
      <mesh geometry={nodes['Object2-Mesh'].geometry} material={materials.Gray} />
      <mesh geometry={nodes['Object2-Mesh_1'].geometry} material={materials.ligrey} />
      <mesh geometry={nodes['Object3-Mesh'].geometry} material={materials.Gray} />
      <mesh geometry={nodes['Object3-Mesh_1'].geometry} material={materials.ligrey} />
      <mesh geometry={nodes['Object4-Mesh'].geometry} material={materials.ligrey} />
      <mesh geometry={nodes['Object4-Mesh_1'].geometry} material={materials.Gray} />
      <mesh geometry={nodes['Object5-Mesh'].geometry} material={materials.ligrey} />
      <mesh geometry={nodes['Object5-Mesh_1'].geometry} material={materials.Gray} />
      <mesh geometry={nodes['Object6-Mesh'].geometry} material={materials.ligrey} />
      <mesh geometry={nodes['Object6-Mesh_1'].geometry} material={materials.Gray} />
      /* laptop screen mesh */
      <mesh geometry={nodes['Object6-Mesh_2'].geometry} material={materials.Black} />
      <mesh geometry={nodes['Object7-Mesh'].geometry} material={materials.Gray} />
      <mesh geometry={nodes['Object7-Mesh_1'].geometry} material={materials.ligrey} />
      <mesh geometry={nodes['Object7-Mesh_2'].geometry} material={materials.darker_grey} />
      <mesh geometry={nodes.Object8.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object9.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object10.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object11.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object12.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object13.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object14.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object15.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object16.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object17.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object18.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object19.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object20.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object21.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object22.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object23.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object24.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object25.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object26.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object27.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object28.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object29.geometry} material={materials.Gray} />
      <mesh geometry={nodes['Object30-Mesh'].geometry} material={materials.Gray} />
      <mesh geometry={nodes['Object30-Mesh_1'].geometry} material={materials.darker_grey} />
      <mesh geometry={nodes.Object31.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object32.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object33.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object34.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object35.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object36.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object37.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object38.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object39.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object40.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object41.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object42.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object43.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object44.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object45.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object46.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object47.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object48.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object49.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object50.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object51.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object52.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object53.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object54.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object55.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object56.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object57.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object58.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object59.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object60.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object61.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object62.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object63.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object64.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object65.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object66.geometry} material={materials.Gray} />
      <mesh geometry={nodes.Object67.geometry} material={materials.Gray} />
      <mesh geometry={nodes['Object68-Mesh'].geometry} material={materials.Gray} />
      <mesh geometry={nodes['Object68-Mesh_1'].geometry} material={materials.darker_grey} />
      <mesh geometry={nodes['Object68-Mesh_2'].geometry} material={materials.ligrey} />
    </group>
  )
}

useGLTF.preload('/Model.glb')

export default function DisplayModel() {
  return (
    <Canvas
       camera={{ position: [-10, -85, 50],fov: 50}}
       style={{
          backgroundColor: '#191f24',
          width: '75vw',
          height: '75vh',
       }}
    >
       <ambientLight intensity={1.25} />
       <ambientLight intensity={0.1} />
       <directionalLight intensity={0.4} />
       <Suspense fallback={null}>
          <Model position={[12, 4, -12]} />
          </Suspense>
       <OrbitControls
        
       />
    </Canvas>
 );
}
