/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Model.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat8} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat19} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat18} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat15} />
      <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat17} />
      <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat22} />
      <mesh geometry={nodes['Node-Mesh_7'].geometry} material={materials.mat25} />
      <mesh geometry={nodes['Node-Mesh_8'].geometry} material={materials.mat3} />
    </group>
  )
}

useGLTF.preload('/Model.glb')
